spring:
  application:
    name: system

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://localhost:3306/mall-system
    username: root
    password: 123456
server:
  port: 8003
